spring:
  profiles:
    include: secret
#  datasource:
#    url: db 주소
#    username: username
#    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    hibernate:
#      ddl-auto: update